models = {
    "index": {
        0: 0,
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 8,
        7: 9,
        8: 11,
        9: 12,
        10: 13,
        11: 17,
        12: 18,
        13: 19,
        14: 20,
        15: 22,
        16: 23,
        17: 25,
        18: 26,
        19: 27,
        20: 28,
        21: 30,
        22: 31,
        23: 32,
        24: 33,
        25: 34,
        26: 35,
        27: 36,
        28: 37,
        29: 38,
        30: 40,
        31: 41,
        32: 42,
        33: 43,
        34: 44,
        35: 45,
        36: 46,
        37: 47,
        38: 48,
        39: 49,
        40: 50,
        41: 51,
        42: 52,
        43: 54,
        44: 56,
        45: 58,
        46: 60,
        47: 63,
        48: 64,
        49: 65,
        50: 67,
        51: 72,
    },
    "NluRef": {
        0: "en.map_entity.umls_disease_syndrome_resolver",
        1: "en.classify.bert_sequence.vop_hcp_consult.pipeline",
        2: "en.resolve.cpt.augmented",
        3: "en.resolve.loinc.augmented",
        4: "en.summarize.clinical_guidelines_large.pipeline",
        5: "en.icd10cm_resolver.pipeline",
        6: "en.med_ner.nihss_pipeline",
        7: "en.resolve.icd9.pipeline",
        8: "en.map_entity.rxnorm_resolver.pipe",
        9: "en.resolve.HPO",
        10: "en.classify.bert_sequence.vop_drug_side_effect.pipeline",
        11: "en.explain_doc.clinical_radiology.pipeline",
        12: "en.med_ner.pathogen.pipeline",
        13: "en.resolve.icdo_augmented",
        14: "pt.deid.clinical",
        15: "ro.deid.clinical",
        16: "en.med_ner.sdoh_langtest.pipeline",
        17: "fr.deid_obfuscated",
        18: "en.summarize.clinical_questions.pipeline",
        19: "es.deid.clinical",
        20: "it.deid.clinical",
        21: "ar.deid.clinical",
        22: "en.de_identify.clinical_pipeline",
        23: "de.deid.clinical",
        24: "en.resolve.snomed.findings",
        25: "pt.deid.clinical",
        26: "en.summarize.clinical_jsl_augmented.pipeline",
        27: "en.map_entity.icd10cm_to_snomed.pipe",
        28: "ro.deid.clinical",
        29: "en.map_entity.snomed_to_icd10cm.pipe",
        30: "fr.deid_obfuscated",
        31: "es.deid.clinical",
        32: "ar.deid.clinical",
        33: "de.deid.clinical",
        34: "it.deid.clinical",
        35: "en.explain_doc.era",
        36: "en.de_identify.clinical_pipeline",
        37: "en.summarize.biomedical_pubmed.pipeline",
        38: "en.map_entity.snomed_to_icdo",
        39: "en.explain_doc.clinical_ade",
        40: "en.med_ner.risk_factors.pipeline",
        41: "en.map_entity.rxnorm_to_ndc.pipe",
        42: "en.summarize.radiology.pipeline",
        43: "en.med_ner.anatom.pipeline",
        44: "en.icd10cm.umls.mapping",
        45: "en.med_ner.living_species.pipeline",
        46: "en.icd10_icd9.mapping",
        47: "en.rxnorm.umls.mapping",
        48: "en.med_ner.bionlp.pipeline",
        49: "en.snomed.umls.mapping",
        50: "en.mesh.umls.mapping",
        51: "en.resolve.medication",
    },
    "Title": {
        0: "Extract Disease and Syndrom entities and their UMLS Codes",
        1: "Detect Healthcare Professional Consult documents",
        2: "Extract procedures and measurements and their corresponding CPT codes",
        3: "Extract Laboratory Observations and the corresponding LOINC codes",
        4: "Guideline Summarizer for Asthma & Breast Cancer",
        5: "Extract Clinical Findings and the corresponding ICD10CM codes",
        6: "Extract neurologic deficits related to Stroke Scale (NIHSS)",
        7: "Extract Clinical Findings and the corresponding ICD 9 codes",
        8: "Extract Drugs and the correspondingt RXNORM codes",
        9: "Extract phenotypic abnormalities and the coresponding HPO codes ",
        10: "Detect Drug Side Effect Narratives",
        11: "Extract findings in radiology reports",
        12: "Detect Pathogen, Medical Condition and Medicine",
        13: "Resolve Oncology terminology with ICD-O Taxonomy",
        14: "Clinical De-identification for Portuguese (Obfuscate)",
        15: "Clinical De-identification for Romanian (Obfuscate)",
        16: "Extract Social Determinants of Health",
        17: "Clinical De-identification for French (Obfuscate)",
        18: "Summarize Clinical Question Notes",
        19: "Clinical De-identification for Spanish (Obfuscate)",
        20: "Clinical De-identification for Italian (Obfuscate)",
        21: "Clinical De-identification for Arabic (Obfuscate)",
        22: "Clinical De-identification (Obfuscate)",
        23: "Clinical De-identification for German (Obfuscate)",
        24: "SNOMED Clinical Health Information Coder",
        25: "Clinical De-identification for Portuguese (Mask)",
        26: "Clinical Text Summarization",
        27: "ICD-10-CM to SNOMED Code Mapper",
        28: "Clinical De-identification for Romanian (Mask)",
        29: "SNOMED to ICD-10-CM Code Mapper",
        30: "Clinical De-identification for French (Mask)",
        31: "Clinical De-identification for Spanish (Mask)",
        32: "Clinical De-identification for Arabic (Mask)",
        33: "Clinical De-identification for German (Mask)",
        34: "Clinical De-identification forItalian (Mask)",
        35: "Extract clinical events and find temporal relations (ERA)",
        36: "Clinical De-identification (Mask)",
        37: "Summarize PubMed Research",
        38: "SNOMED Codes to ICDO Codes Mapper",
        39: "Extract Adverse Drug Events (ADE)",
        40: "Extract clinical risk factors",
        41: "RxNorm to NDC Code Converter",
        42: "Summarize Radiology Reports",
        43: "Extract Anatomical Structures",
        44: " ICD-10-CM to UMLS Code Mapper",
        45: "Extract Living Species",
        46: "ICD-10 to ICD-9 Code Converter",
        47: "RxNorm to UMLS Code Mapper",
        48: "Detect Cancer Genetics",
        49: "SNOMED to UMLS Code Mapper",
        50: "MeSH to UMLS Code Mapper",
        51: "Medication Coder",
    },
    "ReleaseID": {
        0: "0.9",
        1: "0.9",
        2: "0.9",
        3: "0.9",
        4: "0.9",
        5: "0.9",
        6: "0.9",
        7: "0.9",
        8: "0.9",
        9: "0.9",
        10: "0.9",
        11: "0.9",
        12: "0.9",
        13: "0.9",
        14: "0.9",
        15: "0.9",
        16: "0.9",
        17: "0.9",
        18: "0.9",
        19: "0.9",
        20: "0.9",
        21: "0.9",
        22: "0.9",
        23: "0.9",
        24: "0.9",
        25: "0.9",
        26: "0.9",
        27: "0.9",
        28: "0.9",
        29: "0.9",
        30: "0.9",
        31: "0.9",
        32: "0.9",
        33: "0.9",
        34: "0.9",
        35: "0.9",
        36: "0.9",
        37: "0.9",
        38: "0.9",
        39: "0.9",
        40: "0.9",
        41: "0.9",
        42: "0.9",
        43: "0.9",
        44: "0.9",
        45: "0.9",
        46: "0.9",
        47: "0.9",
        48: "0.9",
        49: "0.9",
        50: "0.9",
        51: "0.9",
    },
    "BaseModelPath": {
        0: "john_snow_labs_extract_disease_and_syndrom_entities_and_their_umls_codes.johnsnowlabs_folder.en_map_entity_umls_disease_syndrome_resolver",
        1: "john_snow_labs_detect_healthcare_professional_consult_documents.johnsnowlabs_folder.en_classify_bert_sequence_vop_hcp_consult_pipeline",
        2: "john_snow_labs_extract_procedures_and_measurements_and_their_corresponding_cpt_codes.johnsnowlabs_folder.en_resolve_cpt_augmented",
        3: "john_snow_labs_extract_laboratory_observations_and_the_corresponding_loinc_codes.johnsnowlabs_folder.en_resolve_loinc_augmented",
        4: "john_snow_labs_guideline_summarizer_for_asthma___breast_cancer.johnsnowlabs_folder.en_summarize_clinical_guidelines_large_pipeline",
        5: "john_snow_labs_extract_clinical_findings_and_the_corresponding_icd10cm_codes.johnsnowlabs_folder.en_icd10cm_resolver_pipeline",
        6: "john_snow_labs_extract_neurologic_deficits_related_to_stroke_scale_nihss.johnsnowlabs_folder.en_med_ner_nihss_pipeline",
        7: "john_snow_labs_extract_clinical_findings_and_the_corresponding_icd_9_codes.johnsnowlabs_folder.en_resolve_icd9_pipeline",
        8: "john_snow_labs_extract_drugs_and_the_correspondingt_rxnorm_codes.johnsnowlabs_folder.en_map_entity_rxnorm_resolver_pipe",
        9: "john_snow_labs_extract_phenotypic_abnormalities_and_the_coresponding_hpo_codes_.johnsnowlabs_folder.en_resolve_HPO",
        10: "john_snow_labs_detect_drug_side_effect_narratives.johnsnowlabs_folder.en_classify_bert_sequence_vop_drug_side_effect_pipeline",
        11: "john_snow_labs_extract_findings_in_radiology_reports.johnsnowlabs_folder.en_explain_doc_clinical_radiology_pipeline",
        12: "john_snow_labs_detect_pathogen,_medical_condition_and_medicine.johnsnowlabs_folder.en_med_ner_pathogen_pipeline",
        13: "john_snow_labs_resolve_oncology_terminology_with_icd_o_taxonomy.johnsnowlabs_folder.en_resolve_icdo_augmented",
        14: "john_snow_labs_clinical_de_identification_for_portuguese_obfuscate.johnsnowlabs_folder.pt_deid_clinical",
        15: "john_snow_labs_clinical_de_identification_for_romanian_obfuscate.johnsnowlabs_folder.ro_deid_clinical",
        16: "john_snow_labs_extract_social_determinants_of_health.johnsnowlabs_folder.en_med_ner_sdoh_langtest_pipeline",
        17: "john_snow_labs_clinical_de_identification_for_french_obfuscate.johnsnowlabs_folder.fr_deid_obfuscated",
        18: "john_snow_labs_summarize_clinical_question_notes.johnsnowlabs_folder.en_summarize_clinical_questions_pipeline",
        19: "john_snow_labs_clinical_de_identification_for_spanish_obfuscate.johnsnowlabs_folder.es_deid_clinical",
        20: "john_snow_labs_clinical_de_identification_for_italian_obfuscate.johnsnowlabs_folder.it_deid_clinical",
        21: "john_snow_labs_clinical_de_identification_for_arabic_obfuscate.johnsnowlabs_folder.ar_deid_clinical",
        22: "john_snow_labs_clinical_de_identification_obfuscate.johnsnowlabs_folder.en_de_identify_clinical_pipeline",
        23: "john_snow_labs_clinical_de_identification_for_german_obfuscate.johnsnowlabs_folder.de_deid_clinical",
        24: "john_snow_labs_snomed_clinical_health_information_coder.johnsnowlabs_folder.en_resolve_snomed_findings",
        25: "john_snow_labs_clinical_de_identification_for_portuguese_mask.johnsnowlabs_folder.pt_deid_clinical",
        26: "john_snow_labs_clinical_text_summarization.johnsnowlabs_folder.en_summarize_clinical_jsl_augmented_pipeline",
        27: "john_snow_labs_icd_10_cm_to_snomed_code_mapper.johnsnowlabs_folder.en_map_entity_icd10cm_to_snomed_pipe",
        28: "john_snow_labs_clinical_de_identification_for_romanian_mask.johnsnowlabs_folder.ro_deid_clinical",
        29: "john_snow_labs_snomed_to_icd_10_cm_code_mapper.johnsnowlabs_folder.en_map_entity_snomed_to_icd10cm_pipe",
        30: "john_snow_labs_clinical_de_identification_for_french_mask.johnsnowlabs_folder.fr_deid_obfuscated",
        31: "john_snow_labs_clinical_de_identification_for_spanish_mask.johnsnowlabs_folder.es_deid_clinical",
        32: "john_snow_labs_clinical_de_identification_for_arabic_mask.johnsnowlabs_folder.ar_deid_clinical",
        33: "john_snow_labs_clinical_de_identification_for_german_mask.johnsnowlabs_folder.de_deid_clinical",
        34: "john_snow_labs_clinical_de_identification_foritalian_mask.johnsnowlabs_folder.it_deid_clinical",
        35: "john_snow_labs_extract_clinical_events_and_find_temporal_relations_era.johnsnowlabs_folder.en_explain_doc_era",
        36: "john_snow_labs_clinical_de_identification_mask.johnsnowlabs_folder.en_de_identify_clinical_pipeline",
        37: "john_snow_labs_summarize_pubmed_research.johnsnowlabs_folder.en_summarize_biomedical_pubmed_pipeline",
        38: "john_snow_labs_snomed_codes_to_icdo_codes_mapper.johnsnowlabs_folder.en_map_entity_snomed_to_icdo",
        39: "john_snow_labs_extract_adverse_drug_events_ade.johnsnowlabs_folder.en_explain_doc_clinical_ade",
        40: "john_snow_labs_extract_clinical_risk_factors.johnsnowlabs_folder.en_med_ner_risk_factors_pipeline",
        41: "john_snow_labs_rxnorm_to_ndc_code_converter.johnsnowlabs_folder.en_map_entity_rxnorm_to_ndc_pipe",
        42: "john_snow_labs_summarize_radiology_reports.johnsnowlabs_folder.en_summarize_radiology_pipeline",
        43: "john_snow_labs_extract_anatomical_structures.johnsnowlabs_folder.en_med_ner_anatom_pipeline",
        44: "john_snow_labs__icd_10_cm_to_umls_code_mapper.johnsnowlabs_folder.en_icd10cm_umls_mapping",
        45: "john_snow_labs_extract_living_species.johnsnowlabs_folder.en_med_ner_living_species_pipeline",
        46: "john_snow_labs_icd_10_to_icd_9_code_converter.johnsnowlabs_folder.en_icd10_icd9_mapping",
        47: "john_snow_labs_rxnorm_to_umls_code_mapper.johnsnowlabs_folder.en_rxnorm_umls_mapping",
        48: "john_snow_labs_detect_cancer_genetics.johnsnowlabs_folder.en_med_ner_bionlp_pipeline",
        49: "john_snow_labs_snomed_to_umls_code_mapper.johnsnowlabs_folder.en_snomed_umls_mapping",
        50: "john_snow_labs_mesh_to_umls_code_mapper.johnsnowlabs_folder.en_mesh_umls_mapping",
        51: "john_snow_labs_medication_coder.johnsnowlabs_folder.en_resolve_medication",
    },
    "CpuModelPath": {
        0: "john_snow_labs_extract_disease_and_syndrom_entities_and_their_umls_codes.johnsnowlabs_folder.en_map_entity_umls_disease_syndrome_resolver_cpu",
        1: "john_snow_labs_detect_healthcare_professional_consult_documents.johnsnowlabs_folder.en_classify_bert_sequence_vop_hcp_consult_pipeline_cpu",
        2: "john_snow_labs_extract_procedures_and_measurements_and_their_corresponding_cpt_codes.johnsnowlabs_folder.en_resolve_cpt_augmented_cpu",
        3: "john_snow_labs_extract_laboratory_observations_and_the_corresponding_loinc_codes.johnsnowlabs_folder.en_resolve_loinc_augmented_cpu",
        4: "john_snow_labs_guideline_summarizer_for_asthma___breast_cancer.johnsnowlabs_folder.en_summarize_clinical_guidelines_large_pipeline_cpu",
        5: "john_snow_labs_extract_clinical_findings_and_the_corresponding_icd10cm_codes.johnsnowlabs_folder.en_icd10cm_resolver_pipeline_cpu",
        6: "john_snow_labs_extract_neurologic_deficits_related_to_stroke_scale_nihss.johnsnowlabs_folder.en_med_ner_nihss_pipeline_cpu",
        7: "john_snow_labs_extract_clinical_findings_and_the_corresponding_icd_9_codes.johnsnowlabs_folder.en_resolve_icd9_pipeline_cpu",
        8: "john_snow_labs_extract_drugs_and_the_correspondingt_rxnorm_codes.johnsnowlabs_folder.en_map_entity_rxnorm_resolver_pipe_cpu",
        9: "john_snow_labs_extract_phenotypic_abnormalities_and_the_coresponding_hpo_codes_.johnsnowlabs_folder.en_resolve_HPO_cpu",
        10: "john_snow_labs_detect_drug_side_effect_narratives.johnsnowlabs_folder.en_classify_bert_sequence_vop_drug_side_effect_pipeline_cpu",
        11: "john_snow_labs_extract_findings_in_radiology_reports.johnsnowlabs_folder.en_explain_doc_clinical_radiology_pipeline_cpu",
        12: "john_snow_labs_detect_pathogen,_medical_condition_and_medicine.johnsnowlabs_folder.en_med_ner_pathogen_pipeline_cpu",
        13: "john_snow_labs_resolve_oncology_terminology_with_icd_o_taxonomy.johnsnowlabs_folder.en_resolve_icdo_augmented_cpu",
        14: "john_snow_labs_clinical_de_identification_for_portuguese_obfuscate.johnsnowlabs_folder.pt_deid_clinical_cpu",
        15: "john_snow_labs_clinical_de_identification_for_romanian_obfuscate.johnsnowlabs_folder.ro_deid_clinical_cpu",
        16: "john_snow_labs_extract_social_determinants_of_health.johnsnowlabs_folder.en_med_ner_sdoh_langtest_pipeline_cpu",
        17: "john_snow_labs_clinical_de_identification_for_french_obfuscate.johnsnowlabs_folder.fr_deid_obfuscated_cpu",
        18: "john_snow_labs_summarize_clinical_question_notes.johnsnowlabs_folder.en_summarize_clinical_questions_pipeline_cpu",
        19: "john_snow_labs_clinical_de_identification_for_spanish_obfuscate.johnsnowlabs_folder.es_deid_clinical_cpu",
        20: "john_snow_labs_clinical_de_identification_for_italian_obfuscate.johnsnowlabs_folder.it_deid_clinical_cpu",
        21: "john_snow_labs_clinical_de_identification_for_arabic_obfuscate.johnsnowlabs_folder.ar_deid_clinical_cpu",
        22: "john_snow_labs_clinical_de_identification_obfuscate.johnsnowlabs_folder.en_de_identify_clinical_pipeline_cpu",
        23: "john_snow_labs_clinical_de_identification_for_german_obfuscate.johnsnowlabs_folder.de_deid_clinical_cpu",
        24: "john_snow_labs_snomed_clinical_health_information_coder.johnsnowlabs_folder.en_resolve_snomed_findings_cpu",
        25: "john_snow_labs_clinical_de_identification_for_portuguese_mask.johnsnowlabs_folder.pt_deid_clinical_cpu",
        26: "john_snow_labs_clinical_text_summarization.johnsnowlabs_folder.en_summarize_clinical_jsl_augmented_pipeline_cpu",
        27: "john_snow_labs_icd_10_cm_to_snomed_code_mapper.johnsnowlabs_folder.en_map_entity_icd10cm_to_snomed_pipe_cpu",
        28: "john_snow_labs_clinical_de_identification_for_romanian_mask.johnsnowlabs_folder.ro_deid_clinical_cpu",
        29: "john_snow_labs_snomed_to_icd_10_cm_code_mapper.johnsnowlabs_folder.en_map_entity_snomed_to_icd10cm_pipe_cpu",
        30: "john_snow_labs_clinical_de_identification_for_french_mask.johnsnowlabs_folder.fr_deid_obfuscated_cpu",
        31: "john_snow_labs_clinical_de_identification_for_spanish_mask.johnsnowlabs_folder.es_deid_clinical_cpu",
        32: "john_snow_labs_clinical_de_identification_for_arabic_mask.johnsnowlabs_folder.ar_deid_clinical_cpu",
        33: "john_snow_labs_clinical_de_identification_for_german_mask.johnsnowlabs_folder.de_deid_clinical_cpu",
        34: "john_snow_labs_clinical_de_identification_foritalian_mask.johnsnowlabs_folder.it_deid_clinical_cpu",
        35: "john_snow_labs_extract_clinical_events_and_find_temporal_relations_era.johnsnowlabs_folder.en_explain_doc_era_cpu",
        36: "john_snow_labs_clinical_de_identification_mask.johnsnowlabs_folder.en_de_identify_clinical_pipeline_cpu",
        37: "john_snow_labs_summarize_pubmed_research.johnsnowlabs_folder.en_summarize_biomedical_pubmed_pipeline_cpu",
        38: "john_snow_labs_snomed_codes_to_icdo_codes_mapper.johnsnowlabs_folder.en_map_entity_snomed_to_icdo_cpu",
        39: "john_snow_labs_extract_adverse_drug_events_ade.johnsnowlabs_folder.en_explain_doc_clinical_ade_cpu",
        40: "john_snow_labs_extract_clinical_risk_factors.johnsnowlabs_folder.en_med_ner_risk_factors_pipeline_cpu",
        41: "john_snow_labs_rxnorm_to_ndc_code_converter.johnsnowlabs_folder.en_map_entity_rxnorm_to_ndc_pipe_cpu",
        42: "john_snow_labs_summarize_radiology_reports.johnsnowlabs_folder.en_summarize_radiology_pipeline_cpu",
        43: "john_snow_labs_extract_anatomical_structures.johnsnowlabs_folder.en_med_ner_anatom_pipeline_cpu",
        44: "john_snow_labs__icd_10_cm_to_umls_code_mapper.johnsnowlabs_folder.en_icd10cm_umls_mapping_cpu",
        45: "john_snow_labs_extract_living_species.johnsnowlabs_folder.en_med_ner_living_species_pipeline_cpu",
        46: "john_snow_labs_icd_10_to_icd_9_code_converter.johnsnowlabs_folder.en_icd10_icd9_mapping_cpu",
        47: "john_snow_labs_rxnorm_to_umls_code_mapper.johnsnowlabs_folder.en_rxnorm_umls_mapping_cpu",
        48: "john_snow_labs_detect_cancer_genetics.johnsnowlabs_folder.en_med_ner_bionlp_pipeline_cpu",
        49: "john_snow_labs_snomed_to_umls_code_mapper.johnsnowlabs_folder.en_snomed_umls_mapping_cpu",
        50: "john_snow_labs_mesh_to_umls_code_mapper.johnsnowlabs_folder.en_mesh_umls_mapping_cpu",
        51: "john_snow_labs_medication_coder.johnsnowlabs_folder.en_resolve_medication_cpu",
    },
    "GpuModelPath": {
        0: "john_snow_labs_extract_disease_and_syndrom_entities_and_their_umls_codes.johnsnowlabs_folder.en_map_entity_umls_disease_syndrome_resolver_gpu",
        1: "john_snow_labs_detect_healthcare_professional_consult_documents.johnsnowlabs_folder.en_classify_bert_sequence_vop_hcp_consult_pipeline_gpu",
        2: "john_snow_labs_extract_procedures_and_measurements_and_their_corresponding_cpt_codes.johnsnowlabs_folder.en_resolve_cpt_augmented_gpu",
        3: "john_snow_labs_extract_laboratory_observations_and_the_corresponding_loinc_codes.johnsnowlabs_folder.en_resolve_loinc_augmented_gpu",
        4: "john_snow_labs_guideline_summarizer_for_asthma___breast_cancer.johnsnowlabs_folder.en_summarize_clinical_guidelines_large_pipeline_gpu",
        5: "john_snow_labs_extract_clinical_findings_and_the_corresponding_icd10cm_codes.johnsnowlabs_folder.en_icd10cm_resolver_pipeline_gpu",
        6: "john_snow_labs_extract_neurologic_deficits_related_to_stroke_scale_nihss.johnsnowlabs_folder.en_med_ner_nihss_pipeline_gpu",
        7: "john_snow_labs_extract_clinical_findings_and_the_corresponding_icd_9_codes.johnsnowlabs_folder.en_resolve_icd9_pipeline_gpu",
        8: "john_snow_labs_extract_drugs_and_the_correspondingt_rxnorm_codes.johnsnowlabs_folder.en_map_entity_rxnorm_resolver_pipe_gpu",
        9: "john_snow_labs_extract_phenotypic_abnormalities_and_the_coresponding_hpo_codes_.johnsnowlabs_folder.en_resolve_HPO_gpu",
        10: "john_snow_labs_detect_drug_side_effect_narratives.johnsnowlabs_folder.en_classify_bert_sequence_vop_drug_side_effect_pipeline_gpu",
        11: "john_snow_labs_extract_findings_in_radiology_reports.johnsnowlabs_folder.en_explain_doc_clinical_radiology_pipeline_gpu",
        12: "john_snow_labs_detect_pathogen,_medical_condition_and_medicine.johnsnowlabs_folder.en_med_ner_pathogen_pipeline_gpu",
        13: "john_snow_labs_resolve_oncology_terminology_with_icd_o_taxonomy.johnsnowlabs_folder.en_resolve_icdo_augmented_gpu",
        14: "john_snow_labs_clinical_de_identification_for_portuguese_obfuscate.johnsnowlabs_folder.pt_deid_clinical_gpu",
        15: "john_snow_labs_clinical_de_identification_for_romanian_obfuscate.johnsnowlabs_folder.ro_deid_clinical_gpu",
        16: "john_snow_labs_extract_social_determinants_of_health.johnsnowlabs_folder.en_med_ner_sdoh_langtest_pipeline_gpu",
        17: "john_snow_labs_clinical_de_identification_for_french_obfuscate.johnsnowlabs_folder.fr_deid_obfuscated_gpu",
        18: "john_snow_labs_summarize_clinical_question_notes.johnsnowlabs_folder.en_summarize_clinical_questions_pipeline_gpu",
        19: "john_snow_labs_clinical_de_identification_for_spanish_obfuscate.johnsnowlabs_folder.es_deid_clinical_gpu",
        20: "john_snow_labs_clinical_de_identification_for_italian_obfuscate.johnsnowlabs_folder.it_deid_clinical_gpu",
        21: "john_snow_labs_clinical_de_identification_for_arabic_obfuscate.johnsnowlabs_folder.ar_deid_clinical_gpu",
        22: "john_snow_labs_clinical_de_identification_obfuscate.johnsnowlabs_folder.en_de_identify_clinical_pipeline_gpu",
        23: "john_snow_labs_clinical_de_identification_for_german_obfuscate.johnsnowlabs_folder.de_deid_clinical_gpu",
        24: "john_snow_labs_snomed_clinical_health_information_coder.johnsnowlabs_folder.en_resolve_snomed_findings_gpu",
        25: "john_snow_labs_clinical_de_identification_for_portuguese_mask.johnsnowlabs_folder.pt_deid_clinical_gpu",
        26: "john_snow_labs_clinical_text_summarization.johnsnowlabs_folder.en_summarize_clinical_jsl_augmented_pipeline_gpu",
        27: "john_snow_labs_icd_10_cm_to_snomed_code_mapper.johnsnowlabs_folder.en_map_entity_icd10cm_to_snomed_pipe_gpu",
        28: "john_snow_labs_clinical_de_identification_for_romanian_mask.johnsnowlabs_folder.ro_deid_clinical_gpu",
        29: "john_snow_labs_snomed_to_icd_10_cm_code_mapper.johnsnowlabs_folder.en_map_entity_snomed_to_icd10cm_pipe_gpu",
        30: "john_snow_labs_clinical_de_identification_for_french_mask.johnsnowlabs_folder.fr_deid_obfuscated_gpu",
        31: "john_snow_labs_clinical_de_identification_for_spanish_mask.johnsnowlabs_folder.es_deid_clinical_gpu",
        32: "john_snow_labs_clinical_de_identification_for_arabic_mask.johnsnowlabs_folder.ar_deid_clinical_gpu",
        33: "john_snow_labs_clinical_de_identification_for_german_mask.johnsnowlabs_folder.de_deid_clinical_gpu",
        34: "john_snow_labs_clinical_de_identification_foritalian_mask.johnsnowlabs_folder.it_deid_clinical_gpu",
        35: "john_snow_labs_extract_clinical_events_and_find_temporal_relations_era.johnsnowlabs_folder.en_explain_doc_era_gpu",
        36: "john_snow_labs_clinical_de_identification_mask.johnsnowlabs_folder.en_de_identify_clinical_pipeline_gpu",
        37: "john_snow_labs_summarize_pubmed_research.johnsnowlabs_folder.en_summarize_biomedical_pubmed_pipeline_gpu",
        38: "john_snow_labs_snomed_codes_to_icdo_codes_mapper.johnsnowlabs_folder.en_map_entity_snomed_to_icdo_gpu",
        39: "john_snow_labs_extract_adverse_drug_events_ade.johnsnowlabs_folder.en_explain_doc_clinical_ade_gpu",
        40: "john_snow_labs_extract_clinical_risk_factors.johnsnowlabs_folder.en_med_ner_risk_factors_pipeline_gpu",
        41: "john_snow_labs_rxnorm_to_ndc_code_converter.johnsnowlabs_folder.en_map_entity_rxnorm_to_ndc_pipe_gpu",
        42: "john_snow_labs_summarize_radiology_reports.johnsnowlabs_folder.en_summarize_radiology_pipeline_gpu",
        43: "john_snow_labs_extract_anatomical_structures.johnsnowlabs_folder.en_med_ner_anatom_pipeline_gpu",
        44: "john_snow_labs__icd_10_cm_to_umls_code_mapper.johnsnowlabs_folder.en_icd10cm_umls_mapping_gpu",
        45: "john_snow_labs_extract_living_species.johnsnowlabs_folder.en_med_ner_living_species_pipeline_gpu",
        46: "john_snow_labs_icd_10_to_icd_9_code_converter.johnsnowlabs_folder.en_icd10_icd9_mapping_gpu",
        47: "john_snow_labs_rxnorm_to_umls_code_mapper.johnsnowlabs_folder.en_rxnorm_umls_mapping_gpu",
        48: "john_snow_labs_detect_cancer_genetics.johnsnowlabs_folder.en_med_ner_bionlp_pipeline_gpu",
        49: "john_snow_labs_snomed_to_umls_code_mapper.johnsnowlabs_folder.en_snomed_umls_mapping_gpu",
        50: "john_snow_labs_mesh_to_umls_code_mapper.johnsnowlabs_folder.en_mesh_umls_mapping_gpu",
        51: "john_snow_labs_medication_coder.johnsnowlabs_folder.en_resolve_medication_gpu",
    },
    "ListingId": {
        0: "cf968e18-d8d8-4b9f-b79a-fc4e4a3337a7",
        1: "f29c9e93-8f2d-4969-b472-f3524bdfd883",
        2: "e1a5be5d-b799-4bd1-a664-c31b9c47225f",
        3: "a299884a-7a95-4ddf-96e0-b8594c4290d3",
        4: "153b223a-d73f-479f-a51c-8905434b545d",
        5: "80b9ec4d-c7b8-401c-b177-aa388259f422",
        6: "7afe6ca0-ad66-489b-b2d0-b31b0644d053",
        7: "c2469843-c104-4201-9db5-ba1542823448",
        8: "2b8709b8-4a42-406b-bd93-43172eae07b9",
        9: "d07d7654-d483-4f1d-bb26-13b02197b87f",
        10: "48daa468-2417-437a-b59d-0a06a8935d99",
        11: "a516cbd4-107d-4194-ab02-74095c155f34",
        12: "f52c1b80-794f-457f-bb94-51c5df3ee4be",
        13: "074bbfa7-20ad-4444-8e0a-bc05ff07d6ea",
        14: "8dd5abe1-4df8-41b5-a251-dcf3b161f5c3",
        15: "68c7064e-c1dc-459f-971b-e759bb80810d",
        16: "c23fe435-9461-4d0e-a829-d64f6fecb659",
        17: "eb2042f5-8a50-459c-8884-e11f9573c618",
        18: "251eeb55-2ff6-4e7f-ab92-dbbbabe5c2a4",
        19: "bb9e02a3-3926-4125-bfdf-49cdef5d1ca7",
        20: "ac413121-3018-4a1f-95c1-fadbbf321708",
        21: "b3bac611-ed88-4391-b013-08de4e32a503",
        22: "facfaf55-00f6-496c-a8db-a395631130ec",
        23: "37b22ea9-caf2-429e-ac3c-8b1adb0324cc",
        24: "de82227b-b6d2-4243-857f-071c4b860e8b",
        25: "a5111c18-1c60-4c02-a25a-fa709e819ecd",
        26: "88bf2ba0-fb95-44f8-801d-325a720b6f03",
        27: "1edf9844-470b-4e3a-a157-3ed8c5af89a9",
        28: "8a7ef1cd-c307-4bc7-94c7-4b812a64d3c4",
        29: "5e6f0af1-bcc7-4aa6-a1de-21ca58638fce",
        30: "c600aad0-84c6-4f3d-ae92-5541d3cad171",
        31: "c0456a4c-beeb-4258-9b4a-12e0964e33e5",
        32: "7f5d667a-82a9-48b8-b559-408c589259cd",
        33: "833ccefd-89a0-4e74-8b1d-ddb32181693b",
        34: "51ec7304-2cce-4c60-830e-9fe735ac2a89",
        35: "2a078943-c56d-48b1-a99d-3addb38d688f",
        36: "40f9b4db-ba84-4af1-aba6-57abfba24676",
        37: "9956314c-f7a4-42e0-8081-a7f933ea0c8c",
        38: "e3d2930b-b3bc-4f26-9d35-e81fa9fdd161",
        39: "64d6608b-8341-4b14-8edd-c1a1b31823a6",
        40: "4d973f25-f457-4af7-8ea7-7c3fddaf9493",
        41: "bf4cd2a7-55b5-40fa-b010-c89f54b29ab8",
        42: "0fa941ad-cf3d-4b03-8e46-854e6299afe8",
        43: "7487be7b-0f6d-4aaf-82ef-ea2b1833685a",
        44: "0ee92a5c-35f1-40c9-a7b3-0282e67d9bd1",
        45: "7418db61-8ff0-49db-ae87-756fc17382fc",
        46: "5c645046-e195-4164-a5f5-d3015a7f7647",
        47: "379d172e-cc3f-4c17-ae25-6c83f91e2e6a",
        48: "0a5aebb4-6f73-4af6-96d4-f8d2acfce25d",
        49: "83306cbb-ac15-46e4-86a1-43036dd0c1ec",
        50: "5b4cc372-b9b5-4632-9090-89ddfbef7fe5",
        51: "c0511f92-316e-4106-b09c-b3f55fcca24f",
    },
    "DropDownId": {
        0: "42. Extract Disease and Syndrom entities and their UMLS Codes",
        1: "29. Detect Healthcare Professional Consult documents",
        2: "48. Extract procedures and measurements and their corresponding CPT codes",
        3: "60. Extract Laboratory Observations and the corresponding LOINC codes",
        4: "18. Guideline Summarizer for Asthma & Breast Cancer",
        5: "40. Extract Clinical Findings and the corresponding ICD10CM codes",
        6: "32. Extract neurologic deficits related to Stroke Scale (NIHSS)",
        7: "44. Extract Clinical Findings and the corresponding ICD 9 codes",
        8: "39. Extract Drugs and the correspondingt RXNORM codes",
        9: "47. Extract phenotypic abnormalities and the coresponding HPO codes ",
        10: "30. Detect Drug Side Effect Narratives",
        11: "25. Extract findings in radiology reports",
        12: "35. Detect Pathogen, Medical Condition and Medicine",
        13: "52. Resolve Oncology terminology with ICD-O Taxonomy",
        14: "12. Clinical De-identification for Portuguese (Obfuscate)",
        15: "16. Clinical De-identification for Romanian (Obfuscate)",
        16: "31. Extract Social Determinants of Health",
        17: "10. Clinical De-identification for French (Obfuscate)",
        18: "20. Summarize Clinical Question Notes",
        19: "6. Clinical De-identification for Spanish (Obfuscate)",
        20: "8. Clinical De-identification for Italian (Obfuscate)",
        21: "14. Clinical De-identification for Arabic (Obfuscate)",
        22: "2. Clinical De-identification (Obfuscate)",
        23: "4. Clinical De-identification for German (Obfuscate)",
        24: "56. SNOMED Clinical Health Information Coder",
        25: "11. Clinical De-identification for Portuguese (Mask)",
        26: "22. Clinical Text Summarization",
        27: "49. ICD-10-CM to SNOMED Code Mapper",
        28: "15. Clinical De-identification for Romanian (Mask)",
        29: "58. SNOMED to ICD-10-CM Code Mapper",
        30: "9. Clinical De-identification for French (Mask)",
        31: "5. Clinical De-identification for Spanish (Mask)",
        32: "13. Clinical De-identification for Arabic (Mask)",
        33: "3. Clinical De-identification for German (Mask)",
        34: "7. Clinical De-identification forItalian (Mask)",
        35: None,
        36: "1. Clinical De-identification (Mask)",
        37: "21. Summarize PubMed Research",
        38: "57. SNOMED Codes to ICDO Codes Mapper",
        39: "26. Extract Adverse Drug Events (ADE)",
        40: "33. Extract clinical risk factors",
        41: "54. RxNorm to NDC Code Converter",
        42: "17. Summarize Radiology Reports",
        43: "37. Extract Anatomical Structures",
        44: "43. ICD-10-CM to UMLS Code Mapper",
        45: "36. Extract Living Species",
        46: "50. ICD-10 to ICD-9 Code Converter",
        47: "55. RxNorm to UMLS Code Mapper",
        48: "34. Detect Cancer Genetics",
        49: "59. SNOMED to UMLS Code Mapper",
        50: "51. MeSH to UMLS Code Mapper",
        51: "41. Medication Coder",
    },
    "Id": {
        0: 42.0,
        1: 29.0,
        2: 48.0,
        3: 60.0,
        4: 18.0,
        5: 40.0,
        6: 32.0,
        7: 44.0,
        8: 39.0,
        9: 47.0,
        10: 30.0,
        11: 25.0,
        12: 35.0,
        13: 52.0,
        14: 12.0,
        15: 16.0,
        16: 31.0,
        17: 10.0,
        18: 20.0,
        19: 6.0,
        20: 8.0,
        21: 14.0,
        22: 2.0,
        23: 4.0,
        24: 56.0,
        25: 11.0,
        26: 22.0,
        27: 49.0,
        28: 15.0,
        29: 58.0,
        30: 9.0,
        31: 5.0,
        32: 13.0,
        33: 3.0,
        34: 7.0,
        35: 24.0,
        36: 1.0,
        37: 21.0,
        38: 57.0,
        39: 26.0,
        40: 33.0,
        41: 54.0,
        42: 17.0,
        43: 37.0,
        44: 43.0,
        45: 36.0,
        46: 50.0,
        47: 55.0,
        48: 34.0,
        49: 59.0,
        50: 51.0,
        51: 41.0,
    },
    "Title_d": {
        0: "[Extract Disease and Syndrom entities and their UMLS Codes](./marketplace/consumer/listings/cf968e18-d8d8-4b9f-b79a-fc4e4a3337a7)",
        1: "[Detect Healthcare Professional Consult documents](./marketplace/consumer/listings/f29c9e93-8f2d-4969-b472-f3524bdfd883)",
        2: "[Extract procedures and measurements and their corresponding CPT codes](./marketplace/consumer/listings/e1a5be5d-b799-4bd1-a664-c31b9c47225f)",
        3: "[Extract Laboratory Observations and the corresponding LOINC codes](./marketplace/consumer/listings/a299884a-7a95-4ddf-96e0-b8594c4290d3)",
        4: "[Guideline Summarizer for Asthma & Breast Cancer](./marketplace/consumer/listings/153b223a-d73f-479f-a51c-8905434b545d)",
        5: "[Extract Clinical Findings and the corresponding ICD10CM codes](./marketplace/consumer/listings/80b9ec4d-c7b8-401c-b177-aa388259f422)",
        6: "[Extract neurologic deficits related to Stroke Scale (NIHSS)](./marketplace/consumer/listings/7afe6ca0-ad66-489b-b2d0-b31b0644d053)",
        7: "[Extract Clinical Findings and the corresponding ICD 9 codes](./marketplace/consumer/listings/c2469843-c104-4201-9db5-ba1542823448)",
        8: "[Extract Drugs and the correspondingt RXNORM codes](./marketplace/consumer/listings/2b8709b8-4a42-406b-bd93-43172eae07b9)",
        9: "[Extract phenotypic abnormalities and the coresponding HPO codes ](./marketplace/consumer/listings/d07d7654-d483-4f1d-bb26-13b02197b87f)",
        10: "[Detect Drug Side Effect Narratives](./marketplace/consumer/listings/48daa468-2417-437a-b59d-0a06a8935d99)",
        11: "[Extract findings in radiology reports](./marketplace/consumer/listings/a516cbd4-107d-4194-ab02-74095c155f34)",
        12: "[Detect Pathogen, Medical Condition and Medicine](./marketplace/consumer/listings/f52c1b80-794f-457f-bb94-51c5df3ee4be)",
        13: "[Resolve Oncology terminology with ICD-O Taxonomy](./marketplace/consumer/listings/074bbfa7-20ad-4444-8e0a-bc05ff07d6ea)",
        14: "[Clinical De-identification for Portuguese (Obfuscate)](./marketplace/consumer/listings/8dd5abe1-4df8-41b5-a251-dcf3b161f5c3)",
        15: "[Clinical De-identification for Romanian (Obfuscate)](./marketplace/consumer/listings/68c7064e-c1dc-459f-971b-e759bb80810d)",
        16: "[Extract Social Determinants of Health](./marketplace/consumer/listings/c23fe435-9461-4d0e-a829-d64f6fecb659)",
        17: "[Clinical De-identification for French (Obfuscate)](./marketplace/consumer/listings/eb2042f5-8a50-459c-8884-e11f9573c618)",
        18: "[Summarize Clinical Question Notes](./marketplace/consumer/listings/251eeb55-2ff6-4e7f-ab92-dbbbabe5c2a4)",
        19: "[Clinical De-identification for Spanish (Obfuscate)](./marketplace/consumer/listings/bb9e02a3-3926-4125-bfdf-49cdef5d1ca7)",
        20: "[Clinical De-identification for Italian (Obfuscate)](./marketplace/consumer/listings/ac413121-3018-4a1f-95c1-fadbbf321708)",
        21: "[Clinical De-identification for Arabic (Obfuscate)](./marketplace/consumer/listings/b3bac611-ed88-4391-b013-08de4e32a503)",
        22: "[Clinical De-identification (Obfuscate)](./marketplace/consumer/listings/facfaf55-00f6-496c-a8db-a395631130ec)",
        23: "[Clinical De-identification for German (Obfuscate)](./marketplace/consumer/listings/37b22ea9-caf2-429e-ac3c-8b1adb0324cc)",
        24: "[SNOMED Clinical Health Information Coder](./marketplace/consumer/listings/de82227b-b6d2-4243-857f-071c4b860e8b)",
        25: "[Clinical De-identification for Portuguese (Mask)](./marketplace/consumer/listings/a5111c18-1c60-4c02-a25a-fa709e819ecd)",
        26: "[Clinical Text Summarization](./marketplace/consumer/listings/88bf2ba0-fb95-44f8-801d-325a720b6f03)",
        27: "[ICD-10-CM to SNOMED Code Mapper](./marketplace/consumer/listings/1edf9844-470b-4e3a-a157-3ed8c5af89a9)",
        28: "[Clinical De-identification for Romanian (Mask)](./marketplace/consumer/listings/8a7ef1cd-c307-4bc7-94c7-4b812a64d3c4)",
        29: "[SNOMED to ICD-10-CM Code Mapper](./marketplace/consumer/listings/5e6f0af1-bcc7-4aa6-a1de-21ca58638fce)",
        30: "[Clinical De-identification for French (Mask)](./marketplace/consumer/listings/c600aad0-84c6-4f3d-ae92-5541d3cad171)",
        31: "[Clinical De-identification for Spanish (Mask)](./marketplace/consumer/listings/c0456a4c-beeb-4258-9b4a-12e0964e33e5)",
        32: "[Clinical De-identification for Arabic (Mask)](./marketplace/consumer/listings/7f5d667a-82a9-48b8-b559-408c589259cd)",
        33: "[Clinical De-identification for German (Mask)](./marketplace/consumer/listings/833ccefd-89a0-4e74-8b1d-ddb32181693b)",
        34: "[Clinical De-identification forItalian (Mask)](./marketplace/consumer/listings/51ec7304-2cce-4c60-830e-9fe735ac2a89)",
        35: "[Extract clinical events and find temporal relations (ERA)](./marketplace/consumer/listings/2a078943-c56d-48b1-a99d-3addb38d688f)",
        36: "[Clinical De-identification (Mask)](./marketplace/consumer/listings/40f9b4db-ba84-4af1-aba6-57abfba24676)",
        37: "[Summarize PubMed Research](./marketplace/consumer/listings/9956314c-f7a4-42e0-8081-a7f933ea0c8c)",
        38: "[SNOMED Codes to ICDO Codes Mapper](./marketplace/consumer/listings/e3d2930b-b3bc-4f26-9d35-e81fa9fdd161)",
        39: "[Extract Adverse Drug Events (ADE)](./marketplace/consumer/listings/64d6608b-8341-4b14-8edd-c1a1b31823a6)",
        40: "[Extract clinical risk factors](./marketplace/consumer/listings/4d973f25-f457-4af7-8ea7-7c3fddaf9493)",
        41: "[RxNorm to NDC Code Converter](./marketplace/consumer/listings/bf4cd2a7-55b5-40fa-b010-c89f54b29ab8)",
        42: "[Summarize Radiology Reports](./marketplace/consumer/listings/0fa941ad-cf3d-4b03-8e46-854e6299afe8)",
        43: "[Extract Anatomical Structures](./marketplace/consumer/listings/7487be7b-0f6d-4aaf-82ef-ea2b1833685a)",
        44: "[ ICD-10-CM to UMLS Code Mapper](./marketplace/consumer/listings/0ee92a5c-35f1-40c9-a7b3-0282e67d9bd1)",
        45: "[Extract Living Species](./marketplace/consumer/listings/7418db61-8ff0-49db-ae87-756fc17382fc)",
        46: "[ICD-10 to ICD-9 Code Converter](./marketplace/consumer/listings/5c645046-e195-4164-a5f5-d3015a7f7647)",
        47: "[RxNorm to UMLS Code Mapper](./marketplace/consumer/listings/379d172e-cc3f-4c17-ae25-6c83f91e2e6a)",
        48: "[Detect Cancer Genetics](./marketplace/consumer/listings/0a5aebb4-6f73-4af6-96d4-f8d2acfce25d)",
        49: "[SNOMED to UMLS Code Mapper](./marketplace/consumer/listings/83306cbb-ac15-46e4-86a1-43036dd0c1ec)",
        50: "[MeSH to UMLS Code Mapper](./marketplace/consumer/listings/5b4cc372-b9b5-4632-9090-89ddfbef7fe5)",
        51: "[Medication Coder](./marketplace/consumer/listings/c0511f92-316e-4106-b09c-b3f55fcca24f)",
    },
}


import pandas as pd

models_df = pd.DataFrame(models).reset_index()
