''' division ids '''

from argparse import Namespace

MLB = Namespace()
MLB.AL = Namespace()
MLB.AL.WEST = 200
MLB.AL.EAST = 201
MLB.AL.CENTRAL = 202
MLB.NL = Namespace()
MLB.NL.WEST = 203
MLB.NL.EAST = 204
MLB.NL.CENTRAL = 205
MLB.AMERICAN_LEAGUE = MLB.AL
MLB.NATIONAL_LEAGUE = MLB.NL

AAA = Namespace()
AAA.INT = Namespace()
AAA.INT.EAST = 219
AAA.INT.WEST = 221
AAA.PCL = Namespace()
AAA.PCL.WEST = 231
AAA.PCL.AMERICAN_NORTHERN = 232
AAA.PCL.EAST = 233

AA = Namespace()
AA.EAS = Namespace()
AA.EAS.NORTHEAST = 212
AA.EAS.SOUTHWEST = 213
AA.SOU = Namespace()
AA.SOU.NORTH = 239
AA.SOU.SOUTH = 240
AA.TEX = Namespace()
AA.TEX.NORTH = 241
AA.TEX.SOUTH = 242
AAX = AA

HIGH_A = Namespace()
HIGH_A.SAL = Namespace()
HIGH_A.SAL.NORTH = 237
HIGH_A.SAL.SOUTH = 238
HIGH_A.MID = Namespace()
HIGH_A.MID.EAST = 224
HIGH_A.MID.WEST = 225
AFA = HIGH_A

A = Namespace()
A.CAR = Namespace()
A.CAR.NORTH = 210
A.CAR.SOUTH = 211
A.FSL = Namespace()
A.FSL.EAST = 214
A.FSL.WEST = 215
A.CAL = Namespace()
A.CAL.NORTH = 208
A.CAL.SOUTH = 209
AFX = A

ROK = Namespace()
ROK.ACL = Namespace()
ROK.ACL.EAST = 560
ROK.ACL.WEST = 561
ROK.ACL.CENTRAL = 570
ROK.FCL = Namespace()
ROK.FCL.EAST = 216
ROK.FCL.NORTH = 217
ROK.FCL.SOUTH = 218
ROK.DSL = Namespace()
ROK.DSL.SAN_PEDRO = 246
ROK.DSL.NORTH = 247
ROK.DSL.SOUTH = 248
ROK.DSL.NORTHWEST = 249
ROK.DSL.BASEBALL_CITY = 250
ROK.DSL.NORTHEAST = 401
