# coding: utf-8

"""
    Stock API

    Stock API for Korbyte

    The version of the OpenAPI document: 0.0.11
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from korbyte_api_client.models.details import Details

class TestDetails(unittest.TestCase):
    """Details unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Details:
        """Test Details
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Details`
        """
        model = Details()
        if include_optional:
            return Details(
                id = 56,
                market_capacity = 1.337,
                phone_number = '',
                description = '',
                sic_code = '',
                sic_description = '',
                ticker_root = '',
                homepage_url = '',
                total_employees = 56,
                shares_outstanding = 56,
                weighted_shares_outstanding = 1.337,
                round_lot = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return Details(
        )
        """

    def testDetails(self):
        """Test Details"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
