# coding: utf-8

"""
    Stock API

    Stock API for Korbyte

    The version of the OpenAPI document: 0.0.11
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from korbyte_api_client.api.prepare_api import PrepareApi


class TestPrepareApi(unittest.TestCase):
    """PrepareApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PrepareApi()

    def tearDown(self) -> None:
        pass

    def test_prepare_mapper(self) -> None:
        """Test case for prepare_mapper

        """
        pass

    def test_prepare_prepare(self) -> None:
        """Test case for prepare_prepare

        """
        pass

    def test_prepare_transform(self) -> None:
        """Test case for prepare_transform

        """
        pass


if __name__ == '__main__':
    unittest.main()
