# Generated by Django 4.2.3 on 2023-10-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeasyJobQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('pickled_args', models.BinaryField(null=True)),
                ('pickled_kwargs', models.BinaryField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('doing_now', models.CharField(max_length=255)),
                ('progress', models.IntegerField()),
                ('started', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Enqueud Jobs',
                'ordering': ['-created'],
            },
        ),
    ]
