# Copyright 2016-2023 Cerebras Systems
# SPDX-License-Identifier: BSD-3-Clause

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerebras/pb/workflow/appliance/cluster/client_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerebras_appliance.pb.workflow.appliance.common import common_config_pb2 as cerebras_dot_pb_dot_workflow_dot_appliance_dot_common_dot_common__config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cerebras/pb/workflow/appliance/cluster/client_config.proto',
  package='cerebras',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n:cerebras/pb/workflow/appliance/cluster/client_config.proto\x12\x08\x63\x65rebras\x1a\x39\x63\x65rebras/pb/workflow/appliance/common/common_config.proto\"\x86\x01\n\x10\x43lientCommonInfo\x12\x12\n\nbatch_size\x18\x01 \x01(\x05\x12\x0f\n\x07num_csx\x18\x02 \x01(\x05\x12\x17\n\x0fmax_wgt_servers\x18\x03 \x01(\x05\x12\x1b\n\x13num_workers_per_csx\x18\x04 \x01(\x05\x12\x17\n\x0fmax_act_per_csx\x18\x05 \x01(\x05\"v\n\x11\x43lientCompileInfo\x12\x14\n\x0c\x63irh_content\x18\x01 \x01(\t\x12\x13\n\x0b\x63ompile_dir\x18\x02 \x01(\t\x12\x36\n\x12\x63lient_common_info\x18\x03 \x01(\x0b\x32\x1a.cerebras.ClientCommonInfo\"\x85\x03\n\x11\x43lientExecuteInfo\x12\x19\n\x11\x63\x61\x63he_compile_dir\x18\x01 \x01(\t\x12\x1b\n\x13input_fn_serialized\x18\x02 \x01(\t\x12\x1f\n\x17input_params_serialized\x18\x03 \x01(\t\x12\x13\n\x0btotal_steps\x18\x04 \x01(\x05\x12\x18\n\x10\x63heckpoint_steps\x18\x05 \x01(\x05\x12\x36\n\x12\x63lient_common_info\x18\x06 \x01(\x0b\x32\x1a.cerebras.ClientCommonInfo\x12/\n\x0e\x66ramework_type\x18\x07 \x01(\x0b\x32\x17.cerebras.FrameworkType\x12,\n\x08mode_key\x18\x08 \x01(\x0e\x32\x1a.cerebras.ExecutionModeKey\x12\'\n\x1f\x65nable_dataloader_checkpointing\x18\t \x01(\x08\x12(\n dataloader_state_dict_serialized\x18\n \x01(\t\"\x7f\n\x07SendCRD\x12\x33\n\x0c\x63ompile_info\x18\x01 \x01(\x0b\x32\x1b.cerebras.ClientCompileInfoH\x00\x12\x33\n\x0c\x65xecute_info\x18\x02 \x01(\x0b\x32\x1b.cerebras.ClientExecuteInfoH\x00\x42\n\n\x08job_info\"W\n\x07RecvCRD\x12\x19\n\x11\x63\x61\x63he_compile_dir\x18\x01 \x01(\t\x12\x31\n\x0f\x63luster_details\x18\x02 \x01(\x0b\x32\x18.cerebras.ClusterDetailsb\x06proto3'
  ,
  dependencies=[cerebras_dot_pb_dot_workflow_dot_appliance_dot_common_dot_common__config__pb2.DESCRIPTOR,])




_CLIENTCOMMONINFO = _descriptor.Descriptor(
  name='ClientCommonInfo',
  full_name='cerebras.ClientCommonInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='cerebras.ClientCommonInfo.batch_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_csx', full_name='cerebras.ClientCommonInfo.num_csx', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_wgt_servers', full_name='cerebras.ClientCommonInfo.max_wgt_servers', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_workers_per_csx', full_name='cerebras.ClientCommonInfo.num_workers_per_csx', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_act_per_csx', full_name='cerebras.ClientCommonInfo.max_act_per_csx', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=266,
)


_CLIENTCOMPILEINFO = _descriptor.Descriptor(
  name='ClientCompileInfo',
  full_name='cerebras.ClientCompileInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cirh_content', full_name='cerebras.ClientCompileInfo.cirh_content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='compile_dir', full_name='cerebras.ClientCompileInfo.compile_dir', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_common_info', full_name='cerebras.ClientCompileInfo.client_common_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=386,
)


_CLIENTEXECUTEINFO = _descriptor.Descriptor(
  name='ClientExecuteInfo',
  full_name='cerebras.ClientExecuteInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cache_compile_dir', full_name='cerebras.ClientExecuteInfo.cache_compile_dir', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_fn_serialized', full_name='cerebras.ClientExecuteInfo.input_fn_serialized', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_params_serialized', full_name='cerebras.ClientExecuteInfo.input_params_serialized', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_steps', full_name='cerebras.ClientExecuteInfo.total_steps', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='checkpoint_steps', full_name='cerebras.ClientExecuteInfo.checkpoint_steps', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_common_info', full_name='cerebras.ClientExecuteInfo.client_common_info', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='framework_type', full_name='cerebras.ClientExecuteInfo.framework_type', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode_key', full_name='cerebras.ClientExecuteInfo.mode_key', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enable_dataloader_checkpointing', full_name='cerebras.ClientExecuteInfo.enable_dataloader_checkpointing', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataloader_state_dict_serialized', full_name='cerebras.ClientExecuteInfo.dataloader_state_dict_serialized', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=778,
)


_SENDCRD = _descriptor.Descriptor(
  name='SendCRD',
  full_name='cerebras.SendCRD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='compile_info', full_name='cerebras.SendCRD.compile_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='execute_info', full_name='cerebras.SendCRD.execute_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='job_info', full_name='cerebras.SendCRD.job_info',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=780,
  serialized_end=907,
)


_RECVCRD = _descriptor.Descriptor(
  name='RecvCRD',
  full_name='cerebras.RecvCRD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cache_compile_dir', full_name='cerebras.RecvCRD.cache_compile_dir', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cluster_details', full_name='cerebras.RecvCRD.cluster_details', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=909,
  serialized_end=996,
)

_CLIENTCOMPILEINFO.fields_by_name['client_common_info'].message_type = _CLIENTCOMMONINFO
_CLIENTEXECUTEINFO.fields_by_name['client_common_info'].message_type = _CLIENTCOMMONINFO
_CLIENTEXECUTEINFO.fields_by_name['framework_type'].message_type = cerebras_dot_pb_dot_workflow_dot_appliance_dot_common_dot_common__config__pb2._FRAMEWORKTYPE
_CLIENTEXECUTEINFO.fields_by_name['mode_key'].enum_type = cerebras_dot_pb_dot_workflow_dot_appliance_dot_common_dot_common__config__pb2._EXECUTIONMODEKEY
_SENDCRD.fields_by_name['compile_info'].message_type = _CLIENTCOMPILEINFO
_SENDCRD.fields_by_name['execute_info'].message_type = _CLIENTEXECUTEINFO
_SENDCRD.oneofs_by_name['job_info'].fields.append(
  _SENDCRD.fields_by_name['compile_info'])
_SENDCRD.fields_by_name['compile_info'].containing_oneof = _SENDCRD.oneofs_by_name['job_info']
_SENDCRD.oneofs_by_name['job_info'].fields.append(
  _SENDCRD.fields_by_name['execute_info'])
_SENDCRD.fields_by_name['execute_info'].containing_oneof = _SENDCRD.oneofs_by_name['job_info']
_RECVCRD.fields_by_name['cluster_details'].message_type = cerebras_dot_pb_dot_workflow_dot_appliance_dot_common_dot_common__config__pb2._CLUSTERDETAILS
DESCRIPTOR.message_types_by_name['ClientCommonInfo'] = _CLIENTCOMMONINFO
DESCRIPTOR.message_types_by_name['ClientCompileInfo'] = _CLIENTCOMPILEINFO
DESCRIPTOR.message_types_by_name['ClientExecuteInfo'] = _CLIENTEXECUTEINFO
DESCRIPTOR.message_types_by_name['SendCRD'] = _SENDCRD
DESCRIPTOR.message_types_by_name['RecvCRD'] = _RECVCRD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientCommonInfo = _reflection.GeneratedProtocolMessageType('ClientCommonInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTCOMMONINFO,
  '__module__' : 'cerebras_appliance.pb.workflow.appliance.cluster.client_config_pb2'
  # @@protoc_insertion_point(class_scope:cerebras.ClientCommonInfo)
  })
_sym_db.RegisterMessage(ClientCommonInfo)

ClientCompileInfo = _reflection.GeneratedProtocolMessageType('ClientCompileInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTCOMPILEINFO,
  '__module__' : 'cerebras_appliance.pb.workflow.appliance.cluster.client_config_pb2'
  # @@protoc_insertion_point(class_scope:cerebras.ClientCompileInfo)
  })
_sym_db.RegisterMessage(ClientCompileInfo)

ClientExecuteInfo = _reflection.GeneratedProtocolMessageType('ClientExecuteInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTEXECUTEINFO,
  '__module__' : 'cerebras_appliance.pb.workflow.appliance.cluster.client_config_pb2'
  # @@protoc_insertion_point(class_scope:cerebras.ClientExecuteInfo)
  })
_sym_db.RegisterMessage(ClientExecuteInfo)

SendCRD = _reflection.GeneratedProtocolMessageType('SendCRD', (_message.Message,), {
  'DESCRIPTOR' : _SENDCRD,
  '__module__' : 'cerebras_appliance.pb.workflow.appliance.cluster.client_config_pb2'
  # @@protoc_insertion_point(class_scope:cerebras.SendCRD)
  })
_sym_db.RegisterMessage(SendCRD)

RecvCRD = _reflection.GeneratedProtocolMessageType('RecvCRD', (_message.Message,), {
  'DESCRIPTOR' : _RECVCRD,
  '__module__' : 'cerebras_appliance.pb.workflow.appliance.cluster.client_config_pb2'
  # @@protoc_insertion_point(class_scope:cerebras.RecvCRD)
  })
_sym_db.RegisterMessage(RecvCRD)


# @@protoc_insertion_point(module_scope)
