
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-30T10:21:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d09db37e47016582ec1282182acf016f5389e13c",
 "version": "0.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
