# coding: utf-8

"""
    Stock API

    Stock API for Korbyte

    The version of the OpenAPI document: 0.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from korbyte_api_client.models.api_response_empty import ApiResponseEmpty

class TestApiResponseEmpty(unittest.TestCase):
    """ApiResponseEmpty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiResponseEmpty:
        """Test ApiResponseEmpty
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiResponseEmpty`
        """
        model = ApiResponseEmpty()
        if include_optional:
            return ApiResponseEmpty(
                status = '',
                status_code = 56,
                message = '',
                data = None,
                timestamp = '',
                trace = ''
            )
        else:
            return ApiResponseEmpty(
        )
        """

    def testApiResponseEmpty(self):
        """Test ApiResponseEmpty"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
