# Autogenerated by devscripts/update-version.py

__version__ = '2024.01.28.232706'

RELEASE_GIT_HEAD = '41b6cdb4197aaf7ad82bdad6885eb5d5c64acd74'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.01.28.232706dev'
