
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-30T09:34:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c357b8f62c8656341e7b15d8f8aecc04f24cbfbc",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
