VERSION_YEAR = 2024
VERSION_MONTH = int('01')
VERSION_DAY = int('29')
VERSION_HOUR = int('16')
VERSION_MINUTE = int('06')
MAJOR_VERSION = 0
MINOR_VERSION = 11
PATCH_VERSION = 202401291606
version_date = '2024/01/29 16:06'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
