
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-25T11:55:47+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b24422c26ffd950c5eecbdba36b20d1973c3bb5",
 "version": "1.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
