# Generated by Django 5.0.1 on 2024-01-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(help_text='The message of the feedback.', null=True, verbose_name='Message'),
        ),
    ]
