# coding: utf-8

"""
    Stock API

    Stock API for Korbyte

    The version of the OpenAPI document: 0.0.10
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from korbyte_api_client.models.tracking import Tracking

class TestTracking(unittest.TestCase):
    """Tracking unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Tracking:
        """Test Tracking
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Tracking`
        """
        model = Tracking()
        if include_optional:
            return Tracking(
                id = 56,
                daily = True
            )
        else:
            return Tracking(
        )
        """

    def testTracking(self):
        """Test Tracking"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
