from .types import LogAttrs as LogAttrs, LogType as LogType

def Error(value: Exception) -> LogType: ...
def String(key: str, value: str) -> LogType: ...
def Int(key: str, value: int) -> LogType: ...
def Float(key: str, value: float) -> LogType: ...
