# coding: utf-8

"""
    Akridata DS Backend - Core App

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from akridata_dsp.api_client import ApiClient
from akridata_dsp.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class VideoApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_get_sequence_frames(self, request_id, point_id, **kwargs):  # noqa: E501
        """get_get_sequence_frames  # noqa: E501

        Get frame of a sequence  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_get_sequence_frames(request_id, point_id, async_req=True)
        >>> result = thread.get()

        :param request_id: DS Job ID (required)
        :type request_id: str
        :param point_id: point ID (required)
        :type point_id: int
        :param x_api_key: x_api_key header
        :type x_api_key: str
        :param authorization: authorization header
        :type authorization: str
        :param x_akri_workspace: x_akri_workspace header
        :type x_akri_workspace: str
        :param x_akri_user_role: x_akri_user_role header
        :type x_akri_user_role: str
        :param x_akri_auth: x_akri_auth header
        :type x_akri_auth: str
        :param akri_app_mode: akri_app_name header
        :type akri_app_mode: str
        :param akri_org_name: akri_org_name header
        :type akri_org_name: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: GetFramesOfSequenceResponse
        """
        kwargs['_return_http_data_only'] = True
        return self.get_get_sequence_frames_with_http_info(request_id, point_id, **kwargs)  # noqa: E501

    def get_get_sequence_frames_with_http_info(self, request_id, point_id, **kwargs):  # noqa: E501
        """get_get_sequence_frames  # noqa: E501

        Get frame of a sequence  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_get_sequence_frames_with_http_info(request_id, point_id, async_req=True)
        >>> result = thread.get()

        :param request_id: DS Job ID (required)
        :type request_id: str
        :param point_id: point ID (required)
        :type point_id: int
        :param x_api_key: x_api_key header
        :type x_api_key: str
        :param authorization: authorization header
        :type authorization: str
        :param x_akri_workspace: x_akri_workspace header
        :type x_akri_workspace: str
        :param x_akri_user_role: x_akri_user_role header
        :type x_akri_user_role: str
        :param x_akri_auth: x_akri_auth header
        :type x_akri_auth: str
        :param akri_app_mode: akri_app_name header
        :type akri_app_mode: str
        :param akri_org_name: akri_org_name header
        :type akri_org_name: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(GetFramesOfSequenceResponse, status_code(int), headers(HTTPHeaderDict))
        """

        local_var_params = locals()

        all_params = [
            'request_id',
            'point_id',
            'x_api_key',
            'authorization',
            'x_akri_workspace',
            'x_akri_user_role',
            'x_akri_auth',
            'akri_app_mode',
            'akri_org_name'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_get_sequence_frames" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'request_id' is set
        if self.api_client.client_side_validation and local_var_params.get('request_id') is None:  # noqa: E501
            raise ApiValueError("Missing the required parameter `request_id` when calling `get_get_sequence_frames`")  # noqa: E501
        # verify the required parameter 'point_id' is set
        if self.api_client.client_side_validation and local_var_params.get('point_id') is None:  # noqa: E501
            raise ApiValueError("Missing the required parameter `point_id` when calling `get_get_sequence_frames`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if local_var_params.get('request_id') is not None:  # noqa: E501
            query_params.append(('request_id', local_var_params['request_id']))  # noqa: E501
        if local_var_params.get('point_id') is not None:  # noqa: E501
            query_params.append(('point_id', local_var_params['point_id']))  # noqa: E501

        header_params = dict(local_var_params.get('_headers', {}))
        if 'x_api_key' in local_var_params:
            header_params['X-API-KEY'] = local_var_params['x_api_key']  # noqa: E501
        if 'authorization' in local_var_params:
            header_params['authorization'] = local_var_params['authorization']  # noqa: E501
        if 'x_akri_workspace' in local_var_params:
            header_params['X-AKRI-WORKSPACE'] = local_var_params['x_akri_workspace']  # noqa: E501
        if 'x_akri_user_role' in local_var_params:
            header_params['X-AKRI-USER-ROLE'] = local_var_params['x_akri_user_role']  # noqa: E501
        if 'x_akri_auth' in local_var_params:
            header_params['x-akri-auth'] = local_var_params['x_akri_auth']  # noqa: E501
        if 'akri_app_mode' in local_var_params:
            header_params['AKRI-APP-MODE'] = local_var_params['akri_app_mode']  # noqa: E501
        if 'akri_org_name' in local_var_params:
            header_params['AKRI-ORG-NAME'] = local_var_params['akri_org_name']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        response_types_map = {
            200: "GetFramesOfSequenceResponse",
            400: "GetErrorResponse",
            500: "GetErrorResponse",
        }

        return self.api_client.call_api(
            '/ds/vid_snippet/frames', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_types_map=response_types_map,
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
            _request_auth=local_var_params.get('_request_auth'))

    def get_get_video(self, request_id, point_id, **kwargs):  # noqa: E501
        """get_get_video  # noqa: E501

        Get video generate status  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_get_video(request_id, point_id, async_req=True)
        >>> result = thread.get()

        :param request_id: DS Job ID (required)
        :type request_id: str
        :param point_id: Point ID (required)
        :type point_id: int
        :param x_api_key: x_api_key header
        :type x_api_key: str
        :param authorization: authorization header
        :type authorization: str
        :param x_akri_workspace: x_akri_workspace header
        :type x_akri_workspace: str
        :param x_akri_user_role: x_akri_user_role header
        :type x_akri_user_role: str
        :param x_akri_auth: x_akri_auth header
        :type x_akri_auth: str
        :param akri_app_mode: akri_app_name header
        :type akri_app_mode: str
        :param akri_org_name: akri_org_name header
        :type akri_org_name: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: GetVideoStatus
        """
        kwargs['_return_http_data_only'] = True
        return self.get_get_video_with_http_info(request_id, point_id, **kwargs)  # noqa: E501

    def get_get_video_with_http_info(self, request_id, point_id, **kwargs):  # noqa: E501
        """get_get_video  # noqa: E501

        Get video generate status  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_get_video_with_http_info(request_id, point_id, async_req=True)
        >>> result = thread.get()

        :param request_id: DS Job ID (required)
        :type request_id: str
        :param point_id: Point ID (required)
        :type point_id: int
        :param x_api_key: x_api_key header
        :type x_api_key: str
        :param authorization: authorization header
        :type authorization: str
        :param x_akri_workspace: x_akri_workspace header
        :type x_akri_workspace: str
        :param x_akri_user_role: x_akri_user_role header
        :type x_akri_user_role: str
        :param x_akri_auth: x_akri_auth header
        :type x_akri_auth: str
        :param akri_app_mode: akri_app_name header
        :type akri_app_mode: str
        :param akri_org_name: akri_org_name header
        :type akri_org_name: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(GetVideoStatus, status_code(int), headers(HTTPHeaderDict))
        """

        local_var_params = locals()

        all_params = [
            'request_id',
            'point_id',
            'x_api_key',
            'authorization',
            'x_akri_workspace',
            'x_akri_user_role',
            'x_akri_auth',
            'akri_app_mode',
            'akri_org_name'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_get_video" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'request_id' is set
        if self.api_client.client_side_validation and local_var_params.get('request_id') is None:  # noqa: E501
            raise ApiValueError("Missing the required parameter `request_id` when calling `get_get_video`")  # noqa: E501
        # verify the required parameter 'point_id' is set
        if self.api_client.client_side_validation and local_var_params.get('point_id') is None:  # noqa: E501
            raise ApiValueError("Missing the required parameter `point_id` when calling `get_get_video`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if local_var_params.get('request_id') is not None:  # noqa: E501
            query_params.append(('request_id', local_var_params['request_id']))  # noqa: E501
        if local_var_params.get('point_id') is not None:  # noqa: E501
            query_params.append(('point_id', local_var_params['point_id']))  # noqa: E501

        header_params = dict(local_var_params.get('_headers', {}))
        if 'x_api_key' in local_var_params:
            header_params['X-API-KEY'] = local_var_params['x_api_key']  # noqa: E501
        if 'authorization' in local_var_params:
            header_params['authorization'] = local_var_params['authorization']  # noqa: E501
        if 'x_akri_workspace' in local_var_params:
            header_params['X-AKRI-WORKSPACE'] = local_var_params['x_akri_workspace']  # noqa: E501
        if 'x_akri_user_role' in local_var_params:
            header_params['X-AKRI-USER-ROLE'] = local_var_params['x_akri_user_role']  # noqa: E501
        if 'x_akri_auth' in local_var_params:
            header_params['x-akri-auth'] = local_var_params['x_akri_auth']  # noqa: E501
        if 'akri_app_mode' in local_var_params:
            header_params['AKRI-APP-MODE'] = local_var_params['akri_app_mode']  # noqa: E501
        if 'akri_org_name' in local_var_params:
            header_params['AKRI-ORG-NAME'] = local_var_params['akri_org_name']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        response_types_map = {
            200: "GetVideoStatus",
            400: "GetErrorResponse",
            404: "GetErrorResponse",
            500: "GetErrorResponse",
        }

        return self.api_client.call_api(
            '/dsvid_snippet/video', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_types_map=response_types_map,
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
            _request_auth=local_var_params.get('_request_auth'))

    def post_generate_video_snippet(self, **kwargs):  # noqa: E501
        """post_generate_video_snippet  # noqa: E501

        Submit a request to create a video  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.post_generate_video_snippet(async_req=True)
        >>> result = thread.get()

        :param x_api_key: x_api_key header
        :type x_api_key: str
        :param authorization: authorization header
        :type authorization: str
        :param x_akri_workspace: x_akri_workspace header
        :type x_akri_workspace: str
        :param x_akri_user_role: x_akri_user_role header
        :type x_akri_user_role: str
        :param x_akri_auth: x_akri_auth header
        :type x_akri_auth: str
        :param akri_app_mode: akri_app_name header
        :type akri_app_mode: str
        :param akri_org_name: akri_org_name header
        :type akri_org_name: str
        :param video_snippet_generate_request:
        :type video_snippet_generate_request: VideoSnippetGenerateRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Message
        """
        kwargs['_return_http_data_only'] = True
        return self.post_generate_video_snippet_with_http_info(**kwargs)  # noqa: E501

    def post_generate_video_snippet_with_http_info(self, **kwargs):  # noqa: E501
        """post_generate_video_snippet  # noqa: E501

        Submit a request to create a video  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.post_generate_video_snippet_with_http_info(async_req=True)
        >>> result = thread.get()

        :param x_api_key: x_api_key header
        :type x_api_key: str
        :param authorization: authorization header
        :type authorization: str
        :param x_akri_workspace: x_akri_workspace header
        :type x_akri_workspace: str
        :param x_akri_user_role: x_akri_user_role header
        :type x_akri_user_role: str
        :param x_akri_auth: x_akri_auth header
        :type x_akri_auth: str
        :param akri_app_mode: akri_app_name header
        :type akri_app_mode: str
        :param akri_org_name: akri_org_name header
        :type akri_org_name: str
        :param video_snippet_generate_request:
        :type video_snippet_generate_request: VideoSnippetGenerateRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Message, status_code(int), headers(HTTPHeaderDict))
        """

        local_var_params = locals()

        all_params = [
            'x_api_key',
            'authorization',
            'x_akri_workspace',
            'x_akri_user_role',
            'x_akri_auth',
            'akri_app_mode',
            'akri_org_name',
            'video_snippet_generate_request'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method post_generate_video_snippet" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = dict(local_var_params.get('_headers', {}))
        if 'x_api_key' in local_var_params:
            header_params['X-API-KEY'] = local_var_params['x_api_key']  # noqa: E501
        if 'authorization' in local_var_params:
            header_params['authorization'] = local_var_params['authorization']  # noqa: E501
        if 'x_akri_workspace' in local_var_params:
            header_params['X-AKRI-WORKSPACE'] = local_var_params['x_akri_workspace']  # noqa: E501
        if 'x_akri_user_role' in local_var_params:
            header_params['X-AKRI-USER-ROLE'] = local_var_params['x_akri_user_role']  # noqa: E501
        if 'x_akri_auth' in local_var_params:
            header_params['x-akri-auth'] = local_var_params['x_akri_auth']  # noqa: E501
        if 'akri_app_mode' in local_var_params:
            header_params['AKRI-APP-MODE'] = local_var_params['akri_app_mode']  # noqa: E501
        if 'akri_org_name' in local_var_params:
            header_params['AKRI-ORG-NAME'] = local_var_params['akri_org_name']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'video_snippet_generate_request' in local_var_params:
            body_params = local_var_params['video_snippet_generate_request']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        content_types_list = local_var_params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json'],
                'POST', body_params))  # noqa: E501
        if content_types_list:
                header_params['Content-Type'] = content_types_list

        # Authentication setting
        auth_settings = []  # noqa: E501

        response_types_map = {
            201: "Message",
            208: "Message",
            400: "GetErrorResponse",
            422: "GetErrorResponse",
            500: "GetErrorResponse",
        }

        return self.api_client.call_api(
            '/ds/vid_snippet', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_types_map=response_types_map,
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
            _request_auth=local_var_params.get('_request_auth'))
