# coding: utf-8

"""
    Stock API

    Stock API for Korbyte

    The version of the OpenAPI document: 0.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from korbyte_api_client.api.details_api import DetailsApi


class TestDetailsApi(unittest.TestCase):
    """DetailsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DetailsApi()

    def tearDown(self) -> None:
        pass

    def test_details_delete(self) -> None:
        """Test case for details_delete

        """
        pass

    def test_details_load(self) -> None:
        """Test case for details_load

        """
        pass

    def test_details_save(self) -> None:
        """Test case for details_save

        """
        pass


if __name__ == '__main__':
    unittest.main()
