# coding: utf-8

"""
    Stock API

    Stock API for Korbyte

    The version of the OpenAPI document: 0.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from korbyte_api_client.models.date_entry import DateEntry

class TestDateEntry(unittest.TestCase):
    """DateEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DateEntry:
        """Test DateEntry
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DateEntry`
        """
        model = DateEntry()
        if include_optional:
            return DateEntry(
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                values = [
                    1.337
                    ]
            )
        else:
            return DateEntry(
        )
        """

    def testDateEntry(self):
        """Test DateEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
