# coding: utf-8

"""
    Stock API

    Stock API for Korbyte

    The version of the OpenAPI document: 0.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from korbyte_api_client.models.pageable_object import PageableObject

class TestPageableObject(unittest.TestCase):
    """PageableObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageableObject:
        """Test PageableObject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageableObject`
        """
        model = PageableObject()
        if include_optional:
            return PageableObject(
                page_number = 56,
                page_size = 56,
                paged = True,
                unpaged = True,
                offset = 56,
                sort = korbyte_api_client.models.sort_object.SortObject(
                    sorted = True, 
                    unsorted = True, 
                    empty = True, )
            )
        else:
            return PageableObject(
        )
        """

    def testPageableObject(self):
        """Test PageableObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
