# coding: utf-8

"""
    Stock API

    Stock API for Korbyte

    The version of the OpenAPI document: 0.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from korbyte_api_client.api.daily_api import DailyApi


class TestDailyApi(unittest.TestCase):
    """DailyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DailyApi()

    def tearDown(self) -> None:
        pass

    def test_daily_delete(self) -> None:
        """Test case for daily_delete

        """
        pass

    def test_daily_get_all(self) -> None:
        """Test case for daily_get_all

        Get the Shit from the Balls
        """
        pass

    def test_daily_load(self) -> None:
        """Test case for daily_load

        Sync all daily data for a stock
        """
        pass

    def test_daily_save(self) -> None:
        """Test case for daily_save

        """
        pass


if __name__ == '__main__':
    unittest.main()
