
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-30T12:15:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d4cd865628c258a114542aa3ef9dbe4e28fc408",
 "version": "0.7.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
