
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-30T09:49:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ddd1cc712557e6c7acfb80725e50393a71bea7b",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
