
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-30T18:35:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3b512018df40036101399b56c32755e61dedb505",
 "version": "8.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
