
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-26T10:33:46-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "79b1a8dc88b82ca35ec995490618ad73697c354f",
 "version": "v1.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
