from . import settings as settings
from _typeshed import Incomplete
from dataclasses import dataclass
from typing import Dict

LibName: Incomplete
LogLevel: Incomplete
is_configured: bool

@dataclass
class Loggers:
    root_log_level: int
    log_levels: Dict[LibName, LogLevel] = ...
    turn_json: bool = ...
    add_thread: bool = ...
    add_process: bool = ...
    add_level: bool = ...
    add_filepath: bool = ...
    add_time: bool = ...
    def configure(self) -> None: ...
    def __init__(self, root_log_level, log_levels, turn_json, add_thread, add_process, add_level, add_filepath, add_time) -> None: ...
