
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-29T11:22:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b6ebd029abd3b79540b42e4736007eef00a476cb",
 "version": "8.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
