# Copyright 2016-2023 Cerebras Systems
# SPDX-License-Identifier: BSD-3-Clause

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cerebras/pb/workflow/appliance/cluster_mgmt/cluster_mgmt_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cerebras_appliance.pb.workflow.appliance.common import common_config_pb2 as cerebras_dot_pb_dot_workflow_dot_appliance_dot_common_dot_common__config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cerebras/pb/workflow/appliance/cluster_mgmt/cluster_mgmt_config.proto',
  package='cluster.cluster_mgmt_pb',
  syntax='proto3',
  serialized_options=b'Z+cerebras/pb/workflow/appliance/cluster_mgmt',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nEcerebras/pb/workflow/appliance/cluster_mgmt/cluster_mgmt_config.proto\x12\x17\x63luster.cluster_mgmt_pb\x1a\x39\x63\x65rebras/pb/workflow/appliance/common/common_config.proto\"W\n\x07RecvUSR\x12#\n\x08job_mode\x18\x01 \x01(\x0b\x32\x11.cerebras.JobMode\x12\'\n\ndebug_args\x18\x02 \x01(\x0b\x32\x13.cerebras.DebugArgs\"e\n\x07SendUSR\x12\x31\n\x0f\x63luster_details\x18\x01 \x01(\x0b\x32\x18.cerebras.ClusterDetails\x12\'\n\ndebug_args\x18\x02 \x01(\x0b\x32\x13.cerebras.DebugArgsB-Z+cerebras/pb/workflow/appliance/cluster_mgmtb\x06proto3'
  ,
  dependencies=[cerebras_dot_pb_dot_workflow_dot_appliance_dot_common_dot_common__config__pb2.DESCRIPTOR,])




_RECVUSR = _descriptor.Descriptor(
  name='RecvUSR',
  full_name='cluster.cluster_mgmt_pb.RecvUSR',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_mode', full_name='cluster.cluster_mgmt_pb.RecvUSR.job_mode', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='debug_args', full_name='cluster.cluster_mgmt_pb.RecvUSR.debug_args', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=244,
)


_SENDUSR = _descriptor.Descriptor(
  name='SendUSR',
  full_name='cluster.cluster_mgmt_pb.SendUSR',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster_details', full_name='cluster.cluster_mgmt_pb.SendUSR.cluster_details', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='debug_args', full_name='cluster.cluster_mgmt_pb.SendUSR.debug_args', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=347,
)

_RECVUSR.fields_by_name['job_mode'].message_type = cerebras_dot_pb_dot_workflow_dot_appliance_dot_common_dot_common__config__pb2._JOBMODE
_RECVUSR.fields_by_name['debug_args'].message_type = cerebras_dot_pb_dot_workflow_dot_appliance_dot_common_dot_common__config__pb2._DEBUGARGS
_SENDUSR.fields_by_name['cluster_details'].message_type = cerebras_dot_pb_dot_workflow_dot_appliance_dot_common_dot_common__config__pb2._CLUSTERDETAILS
_SENDUSR.fields_by_name['debug_args'].message_type = cerebras_dot_pb_dot_workflow_dot_appliance_dot_common_dot_common__config__pb2._DEBUGARGS
DESCRIPTOR.message_types_by_name['RecvUSR'] = _RECVUSR
DESCRIPTOR.message_types_by_name['SendUSR'] = _SENDUSR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecvUSR = _reflection.GeneratedProtocolMessageType('RecvUSR', (_message.Message,), {
  'DESCRIPTOR' : _RECVUSR,
  '__module__' : 'cerebras_appliance.pb.workflow.appliance.cluster_mgmt.cluster_mgmt_config_pb2'
  # @@protoc_insertion_point(class_scope:cluster.cluster_mgmt_pb.RecvUSR)
  })
_sym_db.RegisterMessage(RecvUSR)

SendUSR = _reflection.GeneratedProtocolMessageType('SendUSR', (_message.Message,), {
  'DESCRIPTOR' : _SENDUSR,
  '__module__' : 'cerebras_appliance.pb.workflow.appliance.cluster_mgmt.cluster_mgmt_config_pb2'
  # @@protoc_insertion_point(class_scope:cluster.cluster_mgmt_pb.SendUSR)
  })
_sym_db.RegisterMessage(SendUSR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
