# Generated by Django 3.2.16 on 2023-12-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blender_id_oauth_client', '0003_alter_oauthuserinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='oauth_user_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='oauthuserinfo',
            name='oauth_user_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AddIndex(
            model_name='oauthtoken',
            index=models.Index(fields=['oauth_user_id'], name='blender_id__oauth_u_d77ab4_idx'),
        ),
    ]
