# coding: utf-8

"""
    Persons Registry API

    This is a API to Persons Registry  # noqa: E501

    OpenAPI spec version: 1.0.4
    Contact: info@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import persons
from persons.models.role_list_item import RoleListItem  # noqa: E501
from persons.rest import ApiException


class TestRoleListItem(unittest.TestCase):
    """RoleListItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoleListItem(self):
        """Test RoleListItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = persons.models.role_list_item.RoleListItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
