# coding: utf-8

"""
    Persons Registry API

    This is a API to Persons Registry  # noqa: E501

    OpenAPI spec version: 1.0.4
    Contact: info@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import persons
from persons.api.developers_api import DevelopersApi  # noqa: E501
from persons.rest import ApiException


class TestDevelopersApi(unittest.TestCase):
    """DevelopersApi unit test stubs"""

    def setUp(self):
        self.api = DevelopersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_info_api(self):
        """Test case for info_api

        vrací servisní informace  # noqa: E501
        """
        pass

    def test_info_api_head(self):
        """Test case for info_api_head

        vrací informaci o dostupnosti služby  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
