# coding: utf-8

"""
    Persons Registry API

    This is a API to Persons Registry  # noqa: E501

    OpenAPI spec version: 1.0.4
    Contact: info@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import persons
from persons.api.manage_api import ManageApi  # noqa: E501
from persons.rest import ApiException


class TestManageApi(unittest.TestCase):
    """ManageApi unit test stubs"""

    def setUp(self):
        self.api = ManageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_check_individuals(self):
        """Test case for check_individuals

        Kontroluje existenci kolekce uživatelů  # noqa: E501
        """
        pass

    def test_check_persons(self):
        """Test case for check_persons

        Kontroluje existenci kolekce subjektů  # noqa: E501
        """
        pass

    def test_check_roles(self):
        """Test case for check_roles

        Kontroluje existenci kolekce rolí  # noqa: E501
        """
        pass

    def test_check_tags(self):
        """Test case for check_tags

        Kontroluje existenci kolekce tagů  # noqa: E501
        """
        pass

    def test_export_individuals(self):
        """Test case for export_individuals

        Exportuje všechny uživatele ve formátu BSON  # noqa: E501
        """
        pass

    def test_export_persons(self):
        """Test case for export_persons

        Exportuje všechny subjekty ve formátu BSON  # noqa: E501
        """
        pass

    def test_export_roles(self):
        """Test case for export_roles

        Exportuje všechny role ve formátu BSON  # noqa: E501
        """
        pass

    def test_export_tags(self):
        """Test case for export_tags

        Exportuje všechny tagy ve formátu BSON  # noqa: E501
        """
        pass

    def test_import_individuals(self):
        """Test case for import_individuals

        Importuje uživatele  # noqa: E501
        """
        pass

    def test_import_individuals_replace(self):
        """Test case for import_individuals_replace

        Nahradí všechny uživatele  # noqa: E501
        """
        pass

    def test_import_persons(self):
        """Test case for import_persons

        Importuje subjekty  # noqa: E501
        """
        pass

    def test_import_persons_replace(self):
        """Test case for import_persons_replace

        Nahradí všechny subjekty  # noqa: E501
        """
        pass

    def test_import_roles(self):
        """Test case for import_roles

        Importuje role  # noqa: E501
        """
        pass

    def test_import_roles_replace(self):
        """Test case for import_roles_replace

        Nahradí všechny role  # noqa: E501
        """
        pass

    def test_import_tags(self):
        """Test case for import_tags

        Importuje tagy  # noqa: E501
        """
        pass

    def test_import_tags_replace(self):
        """Test case for import_tags_replace

        Nahradí všechny tagy  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
