# coding: utf-8

"""
    Persons Registry API

    This is a API to Persons Registry  # noqa: E501

    OpenAPI spec version: 1.0.4
    Contact: info@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import persons
from persons.api.reference_api import ReferenceApi  # noqa: E501
from persons.rest import ApiException


class TestReferenceApi(unittest.TestCase):
    """ReferenceApi unit test stubs"""

    def setUp(self):
        self.api = ReferenceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_reference_person(self):
        """Test case for delete_reference_person

        Odstraní referenční strukturu osoby  # noqa: E501
        """
        pass

    def test_get_reference_person(self):
        """Test case for get_reference_person

        Vrátí subjekt podle referečního uuid  # noqa: E501
        """
        pass

    def test_get_reference_person_list(self):
        """Test case for get_reference_person_list

        Vrátí subjekty s odkazem  # noqa: E501
        """
        pass

    def test_post_reference_person(self):
        """Test case for post_reference_person

        Zapíše referenční strukturu osoby  # noqa: E501
        """
        pass

    def test_put_reference_person(self):
        """Test case for put_reference_person

        Přepíše referenční strukturu osoby  # noqa: E501
        """
        pass

    def test_sync_crzp_person(self):
        """Test case for sync_crzp_person

        Synchronizuje osobu s CRŽP  # noqa: E501
        """
        pass

    def test_sync_person(self):
        """Test case for sync_person

        Synchronizuje osobu  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
