
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-26T17:41:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e438278d1872a5cc5f28d4fc77b5ce1976cc6bc0",
 "version": "2.3.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
