# coding: utf-8

"""
    Persons Registry API

    This is a API to Persons Registry  # noqa: E501

    OpenAPI spec version: 1.0.4
    Contact: info@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import persons
from persons.models.individual_list_type import IndividualListType  # noqa: E501
from persons.rest import ApiException


class TestIndividualListType(unittest.TestCase):
    """IndividualListType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIndividualListType(self):
        """Test IndividualListType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = persons.models.individual_list_type.IndividualListType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
