# coding: utf-8

"""
    Persons Registry API

    This is a API to Persons Registry  # noqa: E501

    OpenAPI spec version: 1.0.4
    Contact: info@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import persons
from persons.api.manage2_api import Manage2Api  # noqa: E501
from persons.rest import ApiException


class TestManage2Api(unittest.TestCase):
    """Manage2Api unit test stubs"""

    def setUp(self):
        self.api = Manage2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_individuals(self):
        """Test case for get_all_individuals

        Vrací všechny uživatele pro Admin Portal  # noqa: E501
        """
        pass

    def test_get_all_persons(self):
        """Test case for get_all_persons

        Vrací všechny subjekty pro Admin Portal  # noqa: E501
        """
        pass

    def test_get_all_roles(self):
        """Test case for get_all_roles

        Vrací všechny role pro Admin Portal  # noqa: E501
        """
        pass

    def test_get_all_tags(self):
        """Test case for get_all_tags

        Vrací všechny tagy pro Admin Portal  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
