# coding: utf-8

"""
    Persons Registry API

    This is a API to Persons Registry  # noqa: E501

    OpenAPI spec version: 1.0.4
    Contact: info@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import persons
from persons.models.geo_point_jtsk_type import GeoPointJtskType  # noqa: E501
from persons.rest import ApiException


class TestGeoPointJtskType(unittest.TestCase):
    """GeoPointJtskType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeoPointJtskType(self):
        """Test GeoPointJtskType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = persons.models.geo_point_jtsk_type.GeoPointJtskType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
