# coding: utf-8

"""
    Persons Registry API

    This is a API to Persons Registry  # noqa: E501

    OpenAPI spec version: 1.0.4
    Contact: info@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import persons
from persons.models.context_type_roles import ContextTypeRoles  # noqa: E501
from persons.rest import ApiException


class TestContextTypeRoles(unittest.TestCase):
    """ContextTypeRoles unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContextTypeRoles(self):
        """Test ContextTypeRoles"""
        # FIXME: construct object with mandatory attributes with example values
        # model = persons.models.context_type_roles.ContextTypeRoles()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
