# coding: utf-8

"""
    Persons Registry API

    This is a API to Persons Registry  # noqa: E501

    OpenAPI spec version: 1.0.4
    Contact: info@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import persons
from persons.models.identifier_type import IdentifierType  # noqa: E501
from persons.rest import ApiException


class TestIdentifierType(unittest.TestCase):
    """IdentifierType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentifierType(self):
        """Test IdentifierType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = persons.models.identifier_type.IdentifierType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
