# Generated by Django 5.0.1 on 2024-01-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_thumbnails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='box',
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='box',
            field=models.CharField(default='', max_length=255),
        ),
    ]
