from _typeshed import Incomplete
from typing import Any, Type

AnyType: Incomplete

def is_optional(type_: Type[Any]): ...
def remove_optional(type_: Type[Any]): ...
def convert_tuple_to_union(type_: AnyType) -> Type[Any]: ...
