# coding: utf-8

"""
    Akridata DS Backend - Core App

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from akridata_dsp.configuration import Configuration


class Blobs(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'blob_idx': 'int',
        'file_paths': 'list[str]',
        'frame_indices': 'list[int]'
    }

    attribute_map = {
        'blob_idx': 'blob_idx',
        'file_paths': 'file_paths',
        'frame_indices': 'frame_indices'
    }

    def __init__(self, blob_idx=None, file_paths=None, frame_indices=None, local_vars_configuration=None):  # noqa: E501
        """Blobs - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._blob_idx = None
        self._file_paths = None
        self._frame_indices = None
        self.discriminator = None

        self.blob_idx = blob_idx
        self.file_paths = file_paths
        self.frame_indices = frame_indices

    @property
    def blob_idx(self):
        """Gets the blob_idx of this Blobs.  # noqa: E501


        :return: The blob_idx of this Blobs.  # noqa: E501
        :rtype: int
        """
        return self._blob_idx

    @blob_idx.setter
    def blob_idx(self, blob_idx):
        """Sets the blob_idx of this Blobs.


        :param blob_idx: The blob_idx of this Blobs.  # noqa: E501
        :type blob_idx: int
        """
        if self.local_vars_configuration.client_side_validation and blob_idx is None:  # noqa: E501
            raise ValueError("Invalid value for `blob_idx`, must not be `None`")  # noqa: E501

        self._blob_idx = blob_idx

    @property
    def file_paths(self):
        """Gets the file_paths of this Blobs.  # noqa: E501


        :return: The file_paths of this Blobs.  # noqa: E501
        :rtype: list[str]
        """
        return self._file_paths

    @file_paths.setter
    def file_paths(self, file_paths):
        """Sets the file_paths of this Blobs.


        :param file_paths: The file_paths of this Blobs.  # noqa: E501
        :type file_paths: list[str]
        """
        if self.local_vars_configuration.client_side_validation and file_paths is None:  # noqa: E501
            raise ValueError("Invalid value for `file_paths`, must not be `None`")  # noqa: E501

        self._file_paths = file_paths

    @property
    def frame_indices(self):
        """Gets the frame_indices of this Blobs.  # noqa: E501


        :return: The frame_indices of this Blobs.  # noqa: E501
        :rtype: list[int]
        """
        return self._frame_indices

    @frame_indices.setter
    def frame_indices(self, frame_indices):
        """Sets the frame_indices of this Blobs.


        :param frame_indices: The frame_indices of this Blobs.  # noqa: E501
        :type frame_indices: list[int]
        """
        if self.local_vars_configuration.client_side_validation and frame_indices is None:  # noqa: E501
            raise ValueError("Invalid value for `frame_indices`, must not be `None`")  # noqa: E501

        self._frame_indices = frame_indices

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Blobs):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Blobs):
            return True

        return self.to_dict() != other.to_dict()
