# coding: utf-8

"""
    Akridata DS Backend - Core App

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from akridata_dsp.configuration import Configuration


class JobCounters(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'num_versions': 'int',
        'num_versions_deleted': 'int',
        'num_versions_materialized': 'int'
    }

    attribute_map = {
        'num_versions': 'num_versions',
        'num_versions_deleted': 'num_versions_deleted',
        'num_versions_materialized': 'num_versions_materialized'
    }

    def __init__(self, num_versions=None, num_versions_deleted=None, num_versions_materialized=None, local_vars_configuration=None):  # noqa: E501
        """JobCounters - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._num_versions = None
        self._num_versions_deleted = None
        self._num_versions_materialized = None
        self.discriminator = None

        self.num_versions = num_versions
        self.num_versions_deleted = num_versions_deleted
        self.num_versions_materialized = num_versions_materialized

    @property
    def num_versions(self):
        """Gets the num_versions of this JobCounters.  # noqa: E501


        :return: The num_versions of this JobCounters.  # noqa: E501
        :rtype: int
        """
        return self._num_versions

    @num_versions.setter
    def num_versions(self, num_versions):
        """Sets the num_versions of this JobCounters.


        :param num_versions: The num_versions of this JobCounters.  # noqa: E501
        :type num_versions: int
        """
        if self.local_vars_configuration.client_side_validation and num_versions is None:  # noqa: E501
            raise ValueError("Invalid value for `num_versions`, must not be `None`")  # noqa: E501

        self._num_versions = num_versions

    @property
    def num_versions_deleted(self):
        """Gets the num_versions_deleted of this JobCounters.  # noqa: E501


        :return: The num_versions_deleted of this JobCounters.  # noqa: E501
        :rtype: int
        """
        return self._num_versions_deleted

    @num_versions_deleted.setter
    def num_versions_deleted(self, num_versions_deleted):
        """Sets the num_versions_deleted of this JobCounters.


        :param num_versions_deleted: The num_versions_deleted of this JobCounters.  # noqa: E501
        :type num_versions_deleted: int
        """
        if self.local_vars_configuration.client_side_validation and num_versions_deleted is None:  # noqa: E501
            raise ValueError("Invalid value for `num_versions_deleted`, must not be `None`")  # noqa: E501

        self._num_versions_deleted = num_versions_deleted

    @property
    def num_versions_materialized(self):
        """Gets the num_versions_materialized of this JobCounters.  # noqa: E501


        :return: The num_versions_materialized of this JobCounters.  # noqa: E501
        :rtype: int
        """
        return self._num_versions_materialized

    @num_versions_materialized.setter
    def num_versions_materialized(self, num_versions_materialized):
        """Sets the num_versions_materialized of this JobCounters.


        :param num_versions_materialized: The num_versions_materialized of this JobCounters.  # noqa: E501
        :type num_versions_materialized: int
        """
        if self.local_vars_configuration.client_side_validation and num_versions_materialized is None:  # noqa: E501
            raise ValueError("Invalid value for `num_versions_materialized`, must not be `None`")  # noqa: E501

        self._num_versions_materialized = num_versions_materialized

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobCounters):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, JobCounters):
            return True

        return self.to_dict() != other.to_dict()
