
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-30T12:56:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f078d793396303774d150ae5ebabb7534420ace",
 "version": "2.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
