from .histograma import calcular_hist
from .histograma import equalizar
from .histograma import descritor_histograma
from .texture_attributes import mean
from .texture_attributes import variance
from .texture_attributes import skewness
from .texture_attributes import kurtosis
from .texture_attributes import energy
from .texture_attributes import entropy
from .convolution import border_ignore
from .convolution import border_reflect
from .convolution import border_zero
from .convolution import border_replicate
from .save import save_file